name: Pull Request Checks

on:
  push:
    branches:
      - !main

jobs:
  code-quality:
    name: Check code quality
    uses: ./.github/workflows/codeql.yaml
  test:
    name: Run tests
    uses: ./.github/workflows/test.yaml
