name: Pull Request Checks

on:
  pull_request:
    types:
      - opened
      - reopened
    branches:
      - main

jobs:
  code-quality:
    name: Check code quality
    uses: ./.github/workflows/codeql.yaml
  test:
    name: Run tests
    uses: ./.github/workflows/test.yaml
