name: Publish to test Pypi

on:
  push:
    branches:
      - main

jobs:
  publish-test:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.10" ]
    steps:
      - uses: actions/checkout@v4
      - name: set up python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
      - name: install dependencies
        run: |
          pip install --user pdm
      - name: publish
        run: |
          pdm publish --repository https://test.pypi.org/legacy/
