name: Publish to test Pypi

on:
  workflow_run:
    workflows: 
      - "Unit tests"
      - "CodeQL"
    branches: 
      - main
    types: 
      - completed

jobs:
  publish-test:

    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    strategy:
      matrix:
        python-version: [ "3.10" ]
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: set up python ${{ matrix.python-version }}
        uses: pdm-project/setup-pdm@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: true
      - name: install dependencies
        run: |
          pdm install --global --project .
      - name: publish
        run: |
          pdm publish --repository https://test.pypi.org/legacy/
