name: Release on Staging

on:
  push:
    branches:
      - main

jobs:
  code-quality:
    name: Check code quality
    uses: ./.github/workflows/callable/codeql.yaml
  test:
    name: Run tests
    uses: ./.github/workflows/callable/test.yaml
  publish:
    name: Publish staging release
    uses: ./.github/workflows/callable/publish-test.yaml
    needs: [code-quality, test]
