name: Release

on:
  release:
    types:
      - published

jobs:
  publish:
    name: Publish release
    permissions:
      contents: read
      id-token: write
      pages: write
    uses: ./.github/workflows/publish.yaml
