name: Release on Staging

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  code-quality:
    name: Check code quality
    uses: ./.github/workflows/codeql.yaml
  test:
    name: Run tests
    uses: ./.github/workflows/test.yaml
  publish:
    name: Publish staging release
    permissions:
      contents: read
      id-token: write
      pages: write
    uses: ./.github/workflows/publish-test.yaml
    needs: [code-quality, test]
