name: Unit tests

on: [ push ]

jobs:
  unit-test:

    runs-on: ubuntu-latest
    strategy:
      # You can use PyPy versions in python-version.
      # For example, pypy2.7 and pypy3.9
      matrix:
        python-version: [ "3.10" ]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
      - name: Install dependencies
        run: |
          pip install --user pdm
          pdm install --global --project .
      - name: Unit tests
        run: |
          coverage run -m pytest -r tests/
          coverage html -i
      - name: Upload coverage
        uses: actions/upload-artifact@v3
        with:
          name: Coverage report
          path: htmlcov/
        if: ${{ always() }}
