name: Unit tests

on: [ push ]

jobs:
  unit-test:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.10" ]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: pdm-project/setup-pdm@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
      - name: Install dependencies
        run: |
          pdm install --global --project .
      - name: Unit tests
        run: |
          coverage run -m pytest -r tests/
          coverage html -i
      - name: Upload coverage
        uses: actions/upload-artifact@v4
        with:
          name: Coverage report
          path: htmlcov/
        if: ${{ always() }}
